name: "wiki.mbirth.de"
description: "All you never wanted to know"
birthday: "2014-05-08 21:23:39 +0200"

url: "http://wiki.mbirth.de"

#permalink: pretty
permalink: none

paginate: 20

markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md

# This is for {% highlight %} blocks
highlighter: rouge

safe: true
lsi: false

encoding: "utf-8"
timezone: "Europe/Berlin"

github:
    project_title: "Wiki"
    project_tagline: "Experimental Wiki with Jekyll"

gems:
    - kramdown
    - jemoji
    - jekyll-sitemap
    - jekyll-coffeescript
    - jekyll-paginate
    - jekyll-redirect-from
    - jekyll-mentions

kramdown:
    input: GFM
    hard_wrap: false
    # This is for fenced code blocks: ~~~
    syntax_highlighter: rouge

defaults:
    -
        scope:
            path: ""   # an empty string here means all files in the project
            type: "posts"  # "post" for Jekyll <=2.2
        values:
            language: en

